// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9VDdOypqrgiOBRkHcax3y8vnBPwCjuN8',
    appId: '1:129043838101:android:5453270417bb2e6b03979c',
    messagingSenderId: '129043838101',
    projectId: 'gleam-island',
    storageBucket: 'gleam-island.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbT0BPHztQdAqWpQli5EzaWtIQeKtLt1A',
    appId: '1:129043838101:ios:d369afe0261f2d3203979c',
    messagingSenderId: '129043838101',
    projectId: 'gleam-island',
    storageBucket: 'gleam-island.appspot.com',
    iosBundleId: 'com.gleam.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8nWDyhU0EeZH1LB3hGlya9cbGKOOohBQ',
    appId: '1:129043838101:web:2acd494b5a96f04703979c',
    messagingSenderId: '129043838101',
    projectId: 'gleam-island',
    authDomain: 'gleam-island.firebaseapp.com',
    storageBucket: 'gleam-island.appspot.com',
    measurementId: 'G-ETQV5R0909',
  );
}
